<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kentico.Xperience.Admin" Version="30.9.1" />
    <PackageVersion Include="Kentico.Xperience.Core" Version="30.9.1" />
    <PackageVersion Include="Kentico.Xperience.WebApp" Version="30.9.1" />
    <PackageVersion Include="kentico.xperience.azurestorage" Version="30.9.1" />
    <PackageVersion Include="kentico.xperience.imageprocessing" Version="30.9.1" />
    <PackageVersion Include="Magick.NET-Q8-AnyCPU" Version="14.8.1" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    <PackageVersion Include="XperienceCommunity.Bynder" Version="1.2.0" />
  </ItemGroup>
</Project>